[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    Tag               docker.*
    Refresh_Interval  5
    Mem_Buf_Limit     50MB
    Skip_Long_Lines   On

# Keep only the useful app logs (including your ask_request JSON)
[FILTER]
    Name   grep
    Match  docker.*
    Regex  log  ask_request|app\.main:ask|uvicorn|ERROR|Exception

[OUTPUT]
    Name                cloudwatch_logs
    Match               docker.*
    region              us-east-1
    log_group_name      /ec2/cloudika/docker
    log_stream_prefix   docker-
    auto_create_group   true
